#pragma once
#include "Shape.h"

enum ShapeIndex
{
	HCTKCODECAINAY, CAR_RIGHT, CAR_LEFT, GRASS_0,
	GRASS_1, GRASS_2, GRASS_3, GRASS_4,
	STONE, STONE_1, BUSH_2, ROAD, TRAIN_RIGHT, TRAIN_LEFT, 
	DOG_STAY_1, DOG_STAY_2, DOG_JUMP_1, DOG_JUMP_2, 
	RAIL, LOG, RIVER, RED_LIGHT, GREEN_LIGHT, 
	BACKGROUND, NEW_GAME_BUTTON, NEW_GAME_BUTTON_HOVER,
	LOAD_GAME_BUTTON, LOAD_GAME_BUTTON_HOVER,
	RANK_BUTTON, RANK_BUTTON_HOVER, SETTING_BUTTON,
	QUIT_BUTTON, QUIT_BUTTON_HOVER,
};

extern std::vector<Shape* > MyShape;
void initShape();
